### ISSUE TITLE
Assert element does not have an attribute

### ISSUE THREAD

**Issue by rawilk** [sinnbeck/laravel-dom-assertions#10]
I think it would make sense to have a method opposite of the `has` method on `AssertElement` to check that certain attributes are not present on an element. Maybe something like this:

```php
$this->get('/test')
    ->assertElementExists('a', function (AssertElement $a) {
        $a->doesntHave('type', 'button');
        $a->has('href', '/foo');
    });
```

To be honest, this is more of a convenience thing for me, as for now I'm wrapping the element I'm testing in a `<div>` and using `doesntContain` to check for it that way but it just takes me longer to parse what my tests are doing when I come back to them at a later date :)

```php
$this->get('/test')
    ->assertElementExists('div', function (AssertElement $div) {
        $div->doesntContain('a', [
            'type' => 'button',
        ]);

        $div->contains('a', [
            'href' => '/foo',
        ]);
    });
```

**Comment by sinnbeck** [comment]
That makes great sense. I am unsure why I didn't add this already. I'm planning on preparing the package for laravel 10 one of the next days, so I might as well just add that as well 👍

**Comment by sinnbeck** [comment]
Sorry for the delay. It is now released
https://github.com/sinnbeck/laravel-dom-assertions/releases/tag/v1.1.2

**Comment by rawilk** [comment]
@sinnbeck No worries; I have no expectations of open source maintainers to do things or get them implemented in a certain amount of time.
