### ISSUE TITLE
Is there a way to find elements containing text in array?

### ISSUE THREAD

**Issue by viktorasbuivydas** [sinnbeck/laravel-dom-assertions#17]
Hello, I couldn't find a way to solve a problem. I am writing a test where I need to find all h2 tags and see if specific text does not appear in these tags.  

Can't write simple assertDontSee because p paragraph can have same text as h2. 

My html tree is similar to this:
```
<div>
   <div>
      <h2>my h2</h2>
      <p>test</p>
   </div>
   <div>
      <h2>my h2</h2>
      <p>test</p>
   </div>
</div>

```

This is my test where I am trying to solve this problem
```
$this->actingAs($user)
            ->get(route('my-route'))
            ->assertElementExists('h2', function (AssertElement $assertElement) {
                $assertElement->doesntContainText('Specific text');
            });
```

Is there a way to get array of elements and use doesntContainText on all items?

**Comment by sinnbeck** [comment]
You can start your assertion at the body tag by simply passing a clousure and then asserting on the content of that
```
    $this->get('nesting')
        ->assertElementExists(function(AssertElement $assert) {
            $assert->doesntContain('h2', [
                'text' => 'foo'
            ]);
        });

**Comment by sinnbeck** [comment]
Did you get it working?

**Comment by sinnbeck** [comment]
As I have not heard back from you I assume the issue is fixed :)

**Comment by viktorasbuivydas** [comment]
Yes, Thank you!
