### ISSUE TITLE
Not working in PHP8.3.8

### ISSUE THREAD

**Issue by maxakropolis** [sinnbeck/laravel-dom-assertions#19]
Tests fail with the following when using PHP8.3.8
```
BadMethodCallException: Call to undefined method Sinnbeck\DomAssertions\Asserts\AssertForm::getParser()
```
Adding
```
    protected function getParser(): DomParser
    {
        return $this->parser;
    }
``` 
to BaseAssert made it work, although what this indicates I don't know - perhaps that the magic __call method is being called rather than the methods in the traits?

**Comment by maxakropolis** [comment]
Yeah - I assume the git action we use (shivammathur/setup-php@v2) is accidentally pulling in 8.3.8 RC1 (I've tested it locally with 8.3.8 RC1) to prove this.

So this is possibly an issue that will resolve itself but it might be something that needs addressing 🤷

**Comment by sinnbeck** [comment]
Sounds like it. But weird that it uses RC instead of stable :) I will conciser installing the RC using docker to try and replicate it.

**Comment by sinnbeck** [comment]
I think this might be related: https://github.com/php/php-src/issues/14480

**Comment by maxakropolis** [comment]
Thanks @sinnbeck - I hoped it was a bug rather than intended behaviour. Hopefully that means we can all just sit on our hands and the problem will correct itself. We've forked a patched version for now to keep our CI working.

**Comment by sinnbeck** [comment]
So it seems they released it with the bug :/ I will start writing a fix for the package

**Comment by sinnbeck** [comment]
Patch is live. https://github.com/sinnbeck/laravel-dom-assertions/releases/tag/v1.5.1

**Comment by maxakropolis** [comment]
Yep - looking good here. Thank you very much 🎉
