### ISSUE TITLE
Pest Compatibility

### ISSUE THREAD

**Issue by rawilk** [sinnbeck/laravel-dom-assertions#6]
I'm not sure if I'm just missing something, but I can't seem to get the assertions to work when testing with Pest. Anytime I try calling a method, like `assertElementExists`, I get this exception:

`BadMethodCallException: Method Illuminate\Http\Response::assertElementExists does not exist.`

I can fix that by Adding the `DomAssertionsServiceProvider` to `getPackageProviders()` in my base test case, however you have it marked as `@internal` which makes me feel like this isn't the right thing to do:

```php
protected function getPackageProviders()
{
    return [
        DomAssertionsServiceProvider::class,
    ];
}
```

Btw, I am using this in a package test suite with Orchestra, so it might be why I need to do that in my test case.

**Comment by sinnbeck** [comment]
Interesting. The package uses pest for all testing internally as well so it should be compatible. But I am unsure if orchestra uses laravels service provider auto load feature. Are you using other testing packages that just work?

It's marked as internal as you shouldn't need to manually load, but if it's an issue when using it in other packages, I will gladly remove the flag

**Comment by sinnbeck** [comment]
Seems it doesn't pick up packages by default

> By default Testbench doesn't enable any package discovery autoloading when running tests, however you can change this to ignore specific package using:

https://packages.tools/testbench/basic/testcase.html#package-auto-discovery

**Comment by rawilk** [comment]
The only testing packages I really use are the parallel and laravel plugins from pest, and the `spatie/phpunit-snapshot-assertions` package. The snapshot assertions package works without needing to register the service provider in my test case, however I still need to use the `MatchesSnapshots` trait in my tests, so it's not really much different.

I'm not against either method, just wanted to be sure I wasn't missing anything for the assertions in this package to become available in the tests. 

I also tried what was suggested in the testbench link, but with no luck. 

As far as the internal flag goes, it doesn't really matter to me much if you remove it or not since AFAIK it's just going to be my IDE that complains about it :).

BTW I'm loving the package so far; I feel a lot more confident in my tests with the assertions from it.

**Comment by sinnbeck** [comment]
Awesome to hear! I'll remove the internal flag from that one file, to ensure your ide doesn't bark at you. New version tomorrow. Let me know if have any problems 👍

**Comment by sinnbeck** [comment]
New version released.

Just curious. Can you tell me when you release an update on your package as well? I would like to see if I can get it working without the manual import :)

**Comment by rawilk** [comment]
I can do that. Should be sometime today yet.

**Comment by rawilk** [comment]
The package that I'm using this in for testing now has a new release:

https://github.com/rawilk/laravel-breadcrumbs

**Comment by sinnbeck** [comment]
Got it working. I added this to TestCase
```
    protected $enablesPackageDiscoveries = true;
```
and ran
```
vendor/bin/testbench package:discover

**Comment by sinnbeck** [comment]
Can this be closed ? :)

**Comment by rawilk** [comment]
Ah I see, I never ran `package:discover` when I tried that.

> Can this be closed ?

Sounds good to me 👍🏼
