### ISSUE TITLE
Asserting text when element contains duplicate spaces and vertical whitespace

### ISSUE THREAD

**Issue by ziadoz** [sinnbeck/laravel-dom-assertions#8]
I've noticed a problem when asserting the text of an element that contains duplicate spaces and vertical whitespace:

```
<div>
    <p class="foobar">
        Foo
        <span>Bar</span>
    </p>
</div>
```

```
$this->assertElementExists('p.foobar', fn ($el) => $el->has('text', 'Foo Bar'));
```

The assertion fails because the normalised text is:

```
Foo
    Bar
```

I started adjusting `Normalize::text()` to replace the offending characters, but it felt like the wrong approach. 

I wondered if allowing the user to supply a function to use for comparison could be a potential solution?

**Comment by sinnbeck** [comment]
Hmm yeah I can see that indeed can be tricky. Normalizing might be necessary, but the expected output can be tricky (as it can be hard to predict). Currently I cannot come up with a cleaner solution that normalizing it from line breaks and excessive indents, but if you or anyone else have a cleaner idea, I am all ears :)

**Comment by sinnbeck** [comment]
I have released a new version with the fix :)
